### ISSUE TITLE
Diagram application hangs with a white screen on MacOS - various releases of MacOS on various Macs - v30.2.55-ibm2beta2 

### ISSUE THREAD

**Issue by pvrbharg** [IBM/it-architecture-diagrams#2]
Hello,

The ibm2beta2 version of MacOS application hangs with a white screen - forcing user to Force Quit the application and loose work - when expanding left side menu options twisty controls for IBM diagramming content. 

The problem is super consistent and super easy to replicate - pretty much almost all the time. 
I tried 4 different MacBook/MacAir laptops and the behavior is consistent, reproducible and easy to arrive at.

See the screen attachments:
![Screenshot 2023-04-27 at 7 44 11 AM](https://user-images.githubusercontent.com/5838902/235159551-8380fcbb-b208-4b77-a655-d9611105ef30.png)
![Screenshot 2023-04-27 at 7 39 38 AM](https://user-images.githubusercontent.com/5838902/235159553-cbfd3d43-0a30-4e19-93e3-690a5de9a840.png)

**Comment by jaywarfield** [comment]
Until the final published version is available, the v30.2.45 beta is intended to be used (identified as Latest release), the v30.2.55 beta is identified as pre-release with a note in the version readme.
